#pragma once

#include "utils.h"

/*
** Assemble human readable instructions (Intel syntax) from 'inst'
** into binary opcodes in 'bytecode' of size 'bytecode_size'.
**
** No need to set '*bytecode or '*bytecode_size' to NULL.
** Do not pass NULL as any parameter.
**
** Returns 0 on success and 1 on error. The error is generated by NASM
** and its content can be read as a null-terminated string in 'bytecode'.
*/

int assemble(const char *inst, uint8_t **bytecode, size_t *bytecode_size);

/*
** To implement
*/

//int disassemble();
